# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/InCAM/server/site_data/scripts/AutoCAM2.0/mainWindow/view.ui'
#
# Created: Fri Dec 13 12:15:02 2024
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 570)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 0))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setWindowTitle("MainWindow")
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_main = QtGui.QHBoxLayout()
        self.horizontalLayout_main.setSpacing(0)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.frame_sidebar = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_sidebar.sizePolicy().hasHeightForWidth())
        self.frame_sidebar.setSizePolicy(sizePolicy)
        self.frame_sidebar.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_sidebar.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_sidebar.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_sidebar.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_sidebar.setObjectName("frame_sidebar")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_sidebar)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sidebar_button_home = QtGui.QToolButton(self.frame_sidebar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_button_home.sizePolicy().hasHeightForWidth())
        self.sidebar_button_home.setSizePolicy(sizePolicy)
        self.sidebar_button_home.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sidebar_button_home.setObjectName("sidebar_button_home")
        self.verticalLayout_6.addWidget(self.sidebar_button_home)
        spacerItem = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem)
        self.sidebar_button_tools = QtGui.QToolButton(self.frame_sidebar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_button_tools.sizePolicy().hasHeightForWidth())
        self.sidebar_button_tools.setSizePolicy(sizePolicy)
        self.sidebar_button_tools.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sidebar_button_tools.setObjectName("sidebar_button_tools")
        self.verticalLayout_6.addWidget(self.sidebar_button_tools)
        spacerItem1 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem1)
        self.sidebar_button_dev_tools = QtGui.QToolButton(self.frame_sidebar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_button_dev_tools.sizePolicy().hasHeightForWidth())
        self.sidebar_button_dev_tools.setSizePolicy(sizePolicy)
        self.sidebar_button_dev_tools.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sidebar_button_dev_tools.setObjectName("sidebar_button_dev_tools")
        self.verticalLayout_6.addWidget(self.sidebar_button_dev_tools)
        spacerItem2 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem2)
        self.sidebar_button_batch = QtGui.QToolButton(self.frame_sidebar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_button_batch.sizePolicy().hasHeightForWidth())
        self.sidebar_button_batch.setSizePolicy(sizePolicy)
        self.sidebar_button_batch.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sidebar_button_batch.setObjectName("sidebar_button_batch")
        self.verticalLayout_6.addWidget(self.sidebar_button_batch)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_main.addWidget(self.frame_sidebar)
        self.frame_center = QtGui.QFrame(self.centralwidget)
        self.frame_center.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_center.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_center.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_center)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_main.addWidget(self.frame_center)
        self.stackedWidget_main = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_main.sizePolicy().hasHeightForWidth())
        self.stackedWidget_main.setSizePolicy(sizePolicy)
        self.stackedWidget_main.setMinimumSize(QtCore.QSize(600, 0))
        self.stackedWidget_main.setMaximumSize(QtCore.QSize(1111111, 16777215))
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_program_tab = QtGui.QWidget()
        self.page_program_tab.setObjectName("page_program_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.page_program_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_process = QtGui.QTabWidget(self.page_program_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_process.sizePolicy().hasHeightForWidth())
        self.tabWidget_process.setSizePolicy(sizePolicy)
        self.tabWidget_process.setMinimumSize(QtCore.QSize(0, 360))
        font = QtGui.QFont()
        font.setFamily("CM Sans CE")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.tabWidget_process.setFont(font)
        self.tabWidget_process.setAutoFillBackground(False)
        self.tabWidget_process.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_process.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_process.setIconSize(QtCore.QSize(50, 80))
        self.tabWidget_process.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_process.setUsesScrollButtons(True)
        self.tabWidget_process.setDocumentMode(False)
        self.tabWidget_process.setTabsClosable(False)
        self.tabWidget_process.setMovable(False)
        self.tabWidget_process.setObjectName("tabWidget_process")
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget = QtGui.QListWidget(self.tab)
        palette = QtGui.QPalette()
        self.listWidget.setPalette(palette)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_5.addWidget(self.listWidget)
        self.tabWidget_process.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget_process.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget_process)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_test = QtGui.QToolButton(self.page_program_tab)
        self.toolButton_test.setObjectName("toolButton_test")
        self.horizontalLayout_4.addWidget(self.toolButton_test)
        self.toolButton_pause = QtGui.QToolButton(self.page_program_tab)
        self.toolButton_pause.setObjectName("toolButton_pause")
        self.horizontalLayout_4.addWidget(self.toolButton_pause)
        self.toolButton_auto_run = QtGui.QToolButton(self.page_program_tab)
        self.toolButton_auto_run.setObjectName("toolButton_auto_run")
        self.horizontalLayout_4.addWidget(self.toolButton_auto_run)
        self.toolButton_auto_select = QtGui.QPushButton(self.page_program_tab)
        self.toolButton_auto_select.setObjectName("toolButton_auto_select")
        self.horizontalLayout_4.addWidget(self.toolButton_auto_select)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.toolButton_program_info = QtGui.QToolButton(self.page_program_tab)
        self.toolButton_program_info.setObjectName("toolButton_program_info")
        self.horizontalLayout_4.addWidget(self.toolButton_program_info)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.stackedWidget_main.addWidget(self.page_program_tab)
        self.page_dev = QtGui.QWidget()
        self.page_dev.setObjectName("page_dev")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_dev)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_dev = QtGui.QVBoxLayout()
        self.verticalLayout_dev.setObjectName("verticalLayout_dev")
        self.verticalLayout_11.addLayout(self.verticalLayout_dev)
        self.stackedWidget_main.addWidget(self.page_dev)
        self.horizontalLayout_main.addWidget(self.stackedWidget_main)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(500, 0))
        self.frame.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(10000000, 16777215))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_log = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_log.sizePolicy().hasHeightForWidth())
        self.tab_log.setSizePolicy(sizePolicy)
        self.tab_log.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_log.setObjectName("tab_log")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_log)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_tab_log = QtGui.QVBoxLayout()
        self.verticalLayout_tab_log.setSpacing(0)
        self.verticalLayout_tab_log.setObjectName("verticalLayout_tab_log")
        self.verticalLayout_8.addLayout(self.verticalLayout_tab_log)
        self.tabWidget.addTab(self.tab_log, "")
        self.tab_program_info = QtGui.QWidget()
        self.tab_program_info.setObjectName("tab_program_info")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_program_info)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_program_info = QtGui.QVBoxLayout()
        self.verticalLayout_program_info.setObjectName("verticalLayout_program_info")
        self.verticalLayout_10.addLayout(self.verticalLayout_program_info)
        self.tabWidget.addTab(self.tab_program_info, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_main.addWidget(self.frame)
        self.verticalLayout_4.addLayout(self.horizontalLayout_main)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_status = QtGui.QHBoxLayout()
        self.horizontalLayout_status.setSpacing(0)
        self.horizontalLayout_status.setContentsMargins(-1, 4, -1, 4)
        self.horizontalLayout_status.setObjectName("horizontalLayout_status")
        self.label_info = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_info.sizePolicy().hasHeightForWidth())
        self.label_info.setSizePolicy(sizePolicy)
        self.label_info.setMinimumSize(QtCore.QSize(0, 0))
        self.label_info.setObjectName("label_info")
        self.horizontalLayout_status.addWidget(self.label_info)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_status.addItem(spacerItem5)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 14))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 16))
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_status.addWidget(self.progressBar)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_status.addItem(spacerItem6)
        self.label_cpu_memory = QtGui.QLabel(self.centralwidget)
        self.label_cpu_memory.setObjectName("label_cpu_memory")
        self.horizontalLayout_status.addWidget(self.label_cpu_memory)
        self.verticalLayout_4.addLayout(self.horizontalLayout_status)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        palette = QtGui.QPalette()
        self.menuFile.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuPrivilage = QtGui.QMenu(self.menuFile)
        self.menuPrivilage.setObjectName("menuPrivilage")
        self.menuMode = QtGui.QMenu(self.menuFile)
        self.menuMode.setObjectName("menuMode")
        MainWindow.setMenuBar(self.menubar)
        self.actionSaveConfig = QtGui.QAction(MainWindow)
        self.actionSaveConfig.setObjectName("actionSaveConfig")
        self.actionCreateProgram = QtGui.QAction(MainWindow)
        self.actionCreateProgram.setObjectName("actionCreateProgram")
        self.actionUser = QtGui.QAction(MainWindow)
        self.actionUser.setObjectName("actionUser")
        self.actionSupervisor = QtGui.QAction(MainWindow)
        self.actionSupervisor.setObjectName("actionSupervisor")
        self.actionDeveloper = QtGui.QAction(MainWindow)
        self.actionDeveloper.setObjectName("actionDeveloper")
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionRelease = QtGui.QAction(MainWindow)
        self.actionRelease.setObjectName("actionRelease")
        self.menuPrivilage.addAction(self.actionUser)
        self.menuPrivilage.addAction(self.actionSupervisor)
        self.menuPrivilage.addAction(self.actionDeveloper)
        self.menuMode.addAction(self.actionTest)
        self.menuMode.addAction(self.actionRelease)
        self.menuFile.addAction(self.actionCreateProgram)
        self.menuFile.addAction(self.actionSaveConfig)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuMode.menuAction())
        self.menuFile.addAction(self.menuPrivilage.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(0)
        self.tabWidget_process.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.sidebar_button_home.setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.sidebar_button_tools.setText(QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.sidebar_button_dev_tools.setText(QtGui.QApplication.translate("MainWindow", "Dev", None, QtGui.QApplication.UnicodeUTF8))
        self.sidebar_button_batch.setText(QtGui.QApplication.translate("MainWindow", "Batch", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_process.setTabText(self.tabWidget_process.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_process.setTabText(self.tabWidget_process.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_test.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_pause.setText(QtGui.QApplication.translate("MainWindow", "PAUSE", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_auto_run.setText(QtGui.QApplication.translate("MainWindow", "AutoRun", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_auto_select.setText(QtGui.QApplication.translate("MainWindow", "Auto Select", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_program_info.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_program_info), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_info.setText(QtGui.QApplication.translate("MainWindow", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cpu_memory.setText(QtGui.QApplication.translate("MainWindow", "CPU : 5% Memory : 3%", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPrivilage.setTitle(QtGui.QApplication.translate("MainWindow", "Privilage", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMode.setTitle(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveConfig.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreateProgram.setText(QtGui.QApplication.translate("MainWindow", "Create Program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUser.setText(QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSupervisor.setText(QtGui.QApplication.translate("MainWindow", "Supervisor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeveloper.setText(QtGui.QApplication.translate("MainWindow", "Developer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRelease.setText(QtGui.QApplication.translate("MainWindow", "Release", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

